Revert "AIDL: Add support to enable 11BE single link MLD SAP from UI"
This reverts commit fa6d374dbd893aa91a9acb016b210a4d709b6647.

external/wpa_supplicant_8/hostapd/aidl/hostapd.cpp:297:13: error: unused function 'getInterfaceMacAddress' [-Werror,-Wunused-function]
std::string getInterfaceMacAddress(const std::string& if_name)

Change-Id: fa08b4179dd522303cd66a1c7a16f93af8f5d2ab
Signed-off-by: TogoFire <togofire@mailfence.com>